### ISSUE TITLE
Use memset for contiguous NOPs

### ISSUE THREAD

**Issue by ghost** [AmyrAhmady/multi-process-gtasa#1]
https://github.com/AmyrAhmady/multi-process-gtasa/blob/977bc61a1bf993d547f82db804750c7a56411695/multi-process-gtasa/main.cpp#L13-L15

Code above is NOP'ing a contiguous block of memory on [0x74872D, 0x748735], with length 9. Separate calls above could be replaced with the following line: `memset((void*)0x74872D, 0x90, 9);`

**Comment by ghost** [comment]
Can't link this issue to the PR, but [here's the link](https://github.com/AmyrAhmady/multi-process-gtasa/pull/2).

**Comment by AmyrAhmady** [comment]
Nice, thanks, I considered using memcpy but this one's cleaner cause otherwise I had to declare an array too
